### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS with OAuth and SSL setup

### ISSUE THREAD

**Issue by sunmakrules** [jupyterhub/zero-to-jupyterhub-k8s#1466]
I am able to setup 'keycloak' authentication and SSL seperately. But as soon as I intergrate the two I end up with too many redirects error.

Note: I have a seperate nginx-ingress controller running in EKS. Hence, my keycloak and jupyterhub setup are type `ClusterIP`. 

Below is the output of my curl command:
`> curl -vvv <jupyterhub_host.xyz.com>`
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: C=US; ST=<redacted>; L=<redacted>; O=<redacted>, Inc.; CN=<jupyterhub_host.xyz.com>
> *  start date: Oct 16 11:45:01 2019 GMT
> *  expire date: Oct 16 12:15:00 2020 GMT
> *  subjectAltName: host "<jupyterhub_host.xyz.com>" matched cert's "jupyterhub_host.xyz.com"
> *  issuer: C=<redacted>; O=<redacted>.; OU=See www.entrust.net/legal-terms; OU=(c) 2012 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1K
> *  SSL certificate verify ok.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> > GET /hub/oauth_login HTTP/2
> > Host: jupyterhub_host.xyz.com
> > Accept: */*
> * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
> < HTTP/2 301 
> < date: Wed, 30 Oct 2019 22:46:28 GMT
> < location: jupyterhub_host.xyz.com:443/hub/oauth_login
> < strict-transport-security: max-age=15724800; includeSubDomains
> < 
> * Connection #0 to host jupyterhub_host.xyz.com left intact

config.yaml:
```
# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
proxy:
  service:
    type: ClusterIP
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 4.1.0
  https:
    type: manual
hub:
  image:
    name: <redacted>
    tag: 0.0.1
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
      c.Spawner.args = ['--NotebookApp.allow_origin=*', '--debug']
      c.LocalAuthenticator.create_system_users = True
      c.JupyterHub.tornado_settings = {
          'headers': {
              'Access-Control-Allow-Origin': '*',
          },
      }
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<redacted>:role/k8s-hub
singleuser:
  image:
    name: <redacted>
    tag: 0.0.1
  cloudMetadata:
    enabled: true
auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      login_service: Okta
      client_id:     master-realm
      username_key:  preferred_username
      userdata_method: GET
      userdata_params: {'state': 'state'}
  scopes:
    - openid
  admin:
    users: ['abc@def.com']
  state:
    enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
        - jupyterhub_host.xyz.com
      secretName: jupyterhub_host.xyz.com
  pathSuffix: ''
```

Helm deployment:
```
helm install \
--name ${DEPLOYMENT_NAMES_MAP['jupyterhub']} \
--namespace ${DEPLOYMENT_NAMES_MAP['jupyterhub']} \
-f ./helm/jupyterhub/values.yaml \
-f ./helm/jupyterhub/generated_values.yaml \
jupyterhub/jupyterhub \
--set auth.state.cryptoKey=key1 \
--set ingress.hosts={<hub_url>} \
--set proxy.secretToken=key2 \
--set hub.extraEnv.JUPYTERHUB_HOST=<hub_url> \
--set hub.extraEnv.OAUTH2_AUTHORIZE_URL=https://<kc_url>/auth/realms/m/protocol/openid-connect/auth \
--set hub.extraEnv.OAUTH2_TOKEN_URL=https://<kc_url>/auth/realms/m/protocol/openid-connect/token \
--set hub.extraEnv.OAUTH2_USERDATA_URL=https://<kc_url>/auth/auth/realms/m/protocol/openid-connect/userinfo \
							--set hub.extraEnv.OAUTH_CALLBACK_URL=https://<hub_url>/hub/oauth_callback \
							--set auth.custom.config.token_url=https:/<kc_url>auth/realms/m/protocol/openid-connect/token\
--set auth.custom.config.userdata_url=https://<kc_url>/auth/realms/m/protocol/openid-connect/userinfo \
--set proxy.https.manual.key="\$(cat certificates/<hub_url>-openssl.key)\" \
--set proxy.https.manual.cert="\$(cat certificates/<hub_url>-cert.pem)\"
```

**Comment by JPMoresmau** [comment]
I have the same two issues (this one and #806). Using 0.8.2 I get #806 (accessing the hub from the outside redirects from 443 to 8443, which breaks the nginx ingress rules and the HTTPS certificates).
If I use the indicated alpha version of 0.9 of the helm chart (and the corresponding hub image), I get too many redirects.
If I revert back to the 0.8.2 chart and replace 8443 by 443 in the deployment and service yaml files, I get too many redirects. At least here I get the proper SSL certificate :-).
I use https type: secret instead of manual
I set the baseUrl of the hub to /hub (I have other ingresses in my cluster)

The browser console shows me 301 responses where the location header value is equal to the request url...

**Comment by JPMoresmau** [comment]
The way I could progress is to add nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" to the ingress annotations, then change the ingress, proxy service and deployment to use 443 instead of 80 or 8443. In this case I don't have any redirect and I can connect to the hub.

**Comment by consideRatio** [comment]
I recall this is fixed post 0.8.2, i don't remember where right out of my head.

**Comment by JPMoresmau** [comment]
Using jupyterhub/k8s-hub:0.9.0-alpha.1.058.002ae04 as the base hub image and 0.9.0-alpha.1.060.6698eb9 as the chart version, I get ERR_TOO_MANY_REDIRECTS, so no this is not fixed.

**Comment by consideRatio** [comment]
The best insight to debug this i think, will be gained from logs on how the user was bouncing around. Was it from A to B to A to B or from C to A to C to A etc.

To find such info, check the logs of the proxy pod and the logs of the hub pod.

Having figured out that, and with info about authenticator used etc, could maybe get someone insightful enough to figure out a solution.

**Comment by JPMoresmau** [comment]
OK, let's me try to give more info. Since everything works with SSL is disabled, the problem is linked to the proxy and ingress configuration. This is what I have in the config:
```
  proxy:
    secretToken: "<random string>"
    https:
      enabled: true
      type: secret
      hosts:
      - <hostname>
      secret:
        name: <secret name>
  ingress:
    enabled: true
    pathSuffix: hub
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts:
    - <hostname>
    tls:
    - secretName: <secretname
      hosts:
      - <hostname>
 ```

I then try to access the URL https://<hostname>/hub/user/admin/notebooks/<foldername>/<notebookname>?kernel_name=python&somekey=somevalue
(the key and value are needed for the custom authenticator)
- nothing happens on the hub (the logs just show the health and /api/routes being requested by the proxy)
- nothing happens on the proxy, this is the log:

```
08:27:09.271 [ConfigProxy] info: Adding route / -> http://10.107.194.186:8081
08:27:09.293 [ConfigProxy] info: Proxying https://0.0.0.0:8443 to http://10.107.194.186:8081
08:27:09.293 [ConfigProxy] info: Proxy API at http://0.0.0.0:8001/api/routes
08:27:09.298 [ConfigProxy] info: Added HTTP to HTTPS redirection from 8000 to 443
08:27:09.299 [ConfigProxy] info: Route added / -> http://10.107.194.186:8081
08:27:15.469 [ConfigProxy] info: 200 GET /api/routes
08:27:15.487 [ConfigProxy] info: 200 GET /api/routes
08:27:15.490 [ConfigProxy] info: Adding route / -> http://10.107.194.186:8081
08:27:15.490 [ConfigProxy] info: Route added / -> http://10.107.194.186:8081
08:27:15.491 [ConfigProxy] info: 201 POST /api/routes/
08:28:15.495 [ConfigProxy] info: 200 GET /api/routes
08:29:15.496 [ConfigProxy] info: 200 GET /api/routes
08:30:15.495 [ConfigProxy] info: 200 GET /api/routes
08:31:15.495 [ConfigProxy] info: 200 GET /api/routes
08:32:15.495 [ConfigProxy] info: 200 GET /api/routes
```
The ingress controller log show
```
10.33.40.52 - - [29/Nov/2019:08:28:46 +0000] "GET /hub/user/admin/notebooks/TestDataSet/NB1?kernel_name=python3&key=value HTTP/2.0" 301 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" 732 0.002 [ns-proxy-public-80] [] 172.17.0.17:8000 5 0.002 301 2c795a58609e3bbceb5492122a905812
10.33.40.52 - - [29/Nov/2019:08:28:46 +0000] "GET /hub/user/admin/notebooks/TestDataSet/NB1?kernel_name=python3&key=value HTTP/2.0" 301 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" 732 0.001 [ns-proxy-public-80] [] 172.17.0.17:8000 5 0.001 301 609311acef57c678138c56c5cd57be06
```
The browser console tells me:
```
Request:
Request URL: https://<hostname>/hub/user/admin/notebooks/TestDataSet/NB1?kernel_name=python3&key=value
Request Method: GET
Status Code: 301 
Remote Address: 10.33.208.107:443
Referrer Policy: no-referrer-when-downgrade
Response:
date: Fri, 29 Nov 2019 08:37:40 GMT
location: https://<hostname>:443/hub/user/admin/notebooks/TestDataSet/NB1?kernel_name=python3&key=value
server: openresty/1.15.8.2
status: 301
strict-transport-security: max-age=15724800; includeSubDomains
```
So the location of the redirect is the same URL as the request, so it's an infinite redirect loop.
It looks like we access the proxy via HTTP from Nginx, and there's a redirect to SSL since we gave SSL information to the proxy. The ingress only supports port 80 (hardcoded in ingress.yaml) it seems. So we have SSL communication to Nginx, then Nginx use unsecured HTTP to connect to the proxy, the proxy goes "mmh, I need SSL", and redirects to SSL, but the result of the redirect goes through Nginx that uses HTTP to talk to the proxy, and the proxy asks for SSL again.
If the proxy uses SSL, surely the ingress should support going directly to the SSL port, and we could configure that ingress to also support  `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`. As I said when I hacked the chart to do everything via the HTTPS port (the ingress, etc.) it worked.

Hope this helps!

**Comment by manics** [comment]
Sounds like an interaction between your external ingress and the internal one used for let-encrypt.

How is your external ingress configured? Does it have it's own https certificate, or are you somehow proxying through to the let-encrypt certificate managed by the Z2JH internal ingress?

**Comment by JPMoresmau** [comment]
I don't use lets-encrypt, as you can see above my proxy tls settings are set to secret. I use the same secret for the ingress and proxy.

**Comment by consideRatio** [comment]
Hmmm "pathSuffix" was new to me, is it something that we consider in the helm chart template for the ingress when we use these provided values to create the ingress resource?

```yaml
  ingress:
    enabled: true
    pathSuffix: hub
    annotations: 
      kubernetes.io/ingress.class: nginx
    hosts:
    - <hostname>
    tls:
    - secretName: <secretname
      hosts:
      - <hostname>
```

If you want traffic to the hub deployment setup on some URL like example.com/myhub
you should set `hub.baseUrl` to that and your ingress should route to that as well which a pathSuffix may do for you but you must ensure that your actual ingress resource got that. If not use rules, the ingress configuration will at least work to bypass rules.

**Comment by drew-simmons** [comment]
@JPMoresmau were you able to get this to work? I'm seeing similar 500 error tls_certificate_verify with using tls ingress and with proxy https disabled.

**Comment by consideRatio** [comment]
I think this issue may be related #1314, but this issue has now spread out to be about too much at the same time, and I can't clearly see what action point is to take to improve this repository at this point. Due to that, I'm closing it.
