### ISSUE TITLE
function "dig" not defined`

### ISSUE THREAD

**Issue by echarles** [jupyterhub/zero-to-jupyterhub-k8s#2234]
### Bug description

Deploying the helm chart (latest main branch) with a go client, I hit

`failed to install release: parse error at (jupyterhub/templates/hub/_helpers-passwords.tpl:35): function "dig" not defined`

**Comment by consideRatio** [comment]
Use latest version of  helm, 3.5+

**Comment by echarles** [comment]
Thx @consideRatio I am using crossplane and have opened an issue issue in their repository https://github.com/crossplane-contrib/provider-helm/issues/93.

**Comment by ocordes** [comment]
Please update the documents. In the installation procedure a requirement of helm > 3.2 only was mentioned which is sufficient until 0.11.1 which was mentioned later ... (this is the latest document...)

**Comment by consideRatio** [comment]
Can you provide a link to that?

This is what i see:

![Screenshot_20210622-101747](https://user-images.githubusercontent.com/3837114/122889622-3cb9a100-d343-11eb-8cf8-e00b520a00d7.png)

**Comment by ocordes** [comment]
Oh, I see, that is in the beginning of the document.  I saw the old requirements in the chapter for the helm installation "The minimum supported version of Helm in Z2JH is 3.2.0."  This is maybe true but inconsistent to the first page! Sorry, since I've went through the whole document 2 years ago, I select only important chapters for reading and updates, so I started directly with helm ;-)

**Comment by consideRatio** [comment]
@ocordes ah I found that reference, it is indeed a documentation bug! I've fixed it in #2272!

**Comment by ivandir** [comment]
This is still an issue with the following tech stack.

Helm: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

Kube: Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.1

**Comment by consideRatio** [comment]
@ivandir you are using a too outdated `helm` if you have this trouble.

I suspect that `provider registry.terraform.io/hashicorp/helm v2.0.2` is to blame for using an outdated `helm` version. This Helm chart is compatible with `helm` the CLI versioned 3.5.0+
